### ISSUE TITLE
Samus Shell (SASH)

### ISSUE THREAD

**Issue by nekobit1** [emilengler/Samus#1]
This name is completely random and not to be confused with Secure Shell. But we could add a feature packed Shell.

**Comment by emilengler** [comment]
Yeah good idea. I first thought to only implement coreutils but that is another good idea :-)

**Comment by nekobit1** [comment]
Honestly, i get that you want it to be "lightweight", but you can really add more to it. Such as features like piping in cat, etc. So in the readme i wouldnt put 100%, i would just remove the percentage as we can always add more in the future

**Comment by emilengler** [comment]
Yeah good idea
