### ISSUE TITLE
Command Arguments, and convert everything to libraries for ease of use

### ISSUE THREAD

**Issue by nekobit1** [emilengler/Samus#2]
Appearently there is a library called Boost which offers arguments with Program_options. (Im not a CPP dev so I may not be sure)

You could also just right command arguments on your own but that would take some time.

Also, libraries would be nice, so we don't have to just use command line only and embed Samus into our programs?

Hint hint: you should actually reference some of the coreutils code which as a [github](https://github.com/coreutils/coreutils) so you can see how these work, but dont be stealing any code :P

**edit:** now that I think about it tools like coreutils didn't make them libraries for use in other tools (since you can implement these things yourself in code without them even better), you should still split up things into some header files for cleaner code.

**Comment by emilengler** [comment]
I acutally took a look at the other repositories.
I am not thinking about using Boost. The problem is that Boost is not in the Public Domain.
I would create my own solution for parsing arguments by I am currently focused more on other porjects than Samus
